# config.yaml
server:
  base_url: "http://0.0.0.0:5000"
credentials:
  username: "nimda"
  password: "nimda"
encryption:
  # Generate this using: from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())
  shared_key: "_2s26tcGkgYMEck901CrmTTaY1YQ-Ly4Buz96jrJACw="
